from . import constants


FPS = 25
WINDOW_WIDTH = 640
WINDOW_HEIGHT = 480
BOX_SIZE = 20
BOARD_WIDTH = 10
BOARD_HEIGHT = 20
MOVE_SIDEWAYS_FREQUENCY = 0.15
MOVE_DOWN_FREQUENCY = 0.1

X_MARGIN = int((WINDOW_WIDTH - BOARD_WIDTH * BOX_SIZE) / 2)
BOTTOM_MARGIN = 5
TOP_MARGIN = WINDOW_HEIGHT - (BOARD_HEIGHT * BOX_SIZE) - BOTTOM_MARGIN

BORDER_COLOR = constants.BLUE
BG_COLOR = constants.BLACK
TEXT_COLOR = constants.WHITE
TEXT_SHADOW_COLOR = constants.GRAY
