from . import constants


FPS = 25
WINDOW_WIDTH = 640
WINDOW_HEIGHT = 480
BOX_SIZE = 20
BOARD_WIDTH = 10
BOARD_HEIGHT = 20
MOVE_SIDEWAYS_FREQUENCY = 0.15
MOVE_DOWN_FREQUENCY = 0.1

XMARGIN = int((WINDOW_WIDTH - BOARD_WIDTH * BOX_SIZE) / 2)
TOPMARGIN = WINDOW_HEIGHT - (BOARD_HEIGHT * BOX_SIZE) - 5

BORDERCOLOR = constants.BLUE
BGCOLOR = constants.BLACK
TEXTCOLOR = constants.WHITE
TEXTSHADOWCOLOR = constants.GRAY
